# frozen_string_literal: true

module FlashCodes
  LOGIN_YAY = 1
  REGISTER_YAY = 2
  WRONG_PASS = 3
  NO_USER = 4
  USER_TAKEN = 5
  PASS_NOT_MATCH = 6
  INTERNAL_SERVER_ERROR = 7
  ALREADY_LOGGED_IN = 8
  SHIT_PASS = 9
  NO_ADMIN_OPS = 10
  NEW_CATEGORY_YAY = 11
  RENAME_CATEGORY_YAY = 12
  DELETE_CATEGORY_YAY = 13
  INVALID_INPUT = 14
  NEW_ARTICLE_YAY = 15
  EDIT_ARTICLE_YAY = 16
  DELETE_ARTICLE_YAY = 17
end